### ISSUE TITLE
 WARN[0001] failed to refresh PUID: a valid HAR file which contains login arkose is required

### ISSUE THREAD

**Issue by huchenz1** [maxduke/go-chatgpt-api#34]
```
[+] Running 1/1
 ✔ Container go-chatgpt-api  Recreated                                                                                                                0.6s
Attaching to go-chatgpt-api
go-chatgpt-api  | success read chat arkose
go-chatgpt-api  | success read chat arkose
go-chatgpt-api  | INFO[0000] service go-chatgpt-api is ready
go-chatgpt-api  | Error getting auth Arkose token
go-chatgpt-api  | WARN[0001] failed to refresh PUID: a valid HAR file which contains login arkose is required
```
请问是HAR文件有问题吗，我是按照[这里](https://github.com/xqdoo00o/ChatGPT-to-API/blob/master/README_ZH.md#har%E6%96%87%E4%BB%B6%E6%B1%A0)操作的，先gpt3对话一下，然后gpt4对话，最后到处har
非常感谢！
```
services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: maxduke/go-chatgpt-api
    ports:
      - 8060:8080
    environment:
      - PORT=
      - TZ=Asia/Shanghai
      - PROXY=
      - OPENAI_EMAIL= xxx
      - OPENAI_PASSWORD=xxx
      - CONTINUE_SIGNAL=
      - ENABLE_HISTORY=
      - IMITATE_ACCESS_TOKEN=
      - IMITATE_API_KEY=xxx
    volumes:
      - ./harPool:/app/harPool
    restart: unless-stopped
```
