### ISSUE TITLE
service go-chatgpt-api is ready    [GIN] 2024/05/15 - 15:40:13 | 500 

### ISSUE THREAD

**Issue by ventusoon** [maxduke/go-chatgpt-api#54]
多次出现500提示，更新最新版也无用。
docker-compose搭建，内容如下
```
version: "3" 
services:
  go-chatgpt-api:
    image: maxduke/go-chatgpt-api:latest
    container_name: go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      #- ENABLE_HEALTHCHECK=True
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock:ro
      - /harPool:/app/harPool
    restart: unless-stopped
```
新建了harPool文件夹，映射到了/app/harPool，har文件已更新，前端使用[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)，模型选不选择gpt-3.5都仍然500 

![微信截图_20240515155451](https://github.com/maxduke/go-chatgpt-api/assets/14863512/87783731-4c98-4f9f-9c0b-295f04e2f431)
